---
name: Pull Requests
on:
  pull_request:
    branches:
      - main
      - 'v*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/protoc-gen-go-hashpb/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}

      - name: Test
        run: make test

      - name: Check repo status
        run: |-
          REPO_STATUS="$(git status --porcelain)"
          if [[ ! -z $REPO_STATUS ]]; then
            echo "::error::Uncommitted changes detected"
            echo "$REPO_STATUS"
            exit 1
          fi
