---
name: Release
on:
  push:
    tags:
      - v*
jobs:
  releaseBinaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Buf plugin registry
        uses: docker/login-action@v1
        with:
          registry: plugins.buf.build
          username: cerbos
          password: ${{ secrets.BUF_TOKEN }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/protoc-gen-go-hashpb/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config=.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
